name: chrona
description: CHRONA Flutter application.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  path: ^1.9.1
  sqflite: ^2.4.2
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  shared_preferences: ^2.5.5
  file_picker: ^10.3.7

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/image.png
    - assets/ring/ring.mp3
    - assets/question/拾年每日一问.json
    - assets/question/特殊日期每日一问.json
    - assets/question/拾年随机问题池_4000.json

