org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true

# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false

# The project is on G: while Flutter plugins are cached on C:, which breaks
# Kotlin's incremental cache path calculations on Windows.
kotlin.incremental=false
